
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "dfefefe@test.com",
    "password": "ddezdR846548"
}
### 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "dfefefe@test.com",
    "password": "ddezdR846548"
}
###
GET http://localhost:3000/api/sauces/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiNDJlOGYzNTc1YjIyYWE1NWQyNzciLCJpYXQiOjE2MzEyNzM3MzMsImV4cCI6MTYzMTM2MDEzM30.Wg5I92-qKlhdtvpj4EZikhyqx5u8Thf_68WZBgzepJc
###
POST http://localhost:3000/api/sauces/6135f8221efae202b683ed4f/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiNDJlOGYzNTc1YjIyYWE1NWQyNzciLCJpYXQiOjE2MzEyNzM3MzMsImV4cCI6MTYzMTM2MDEzM30.Wg5I92-qKlhdtvpj4EZikhyqx5u8Thf_68WZBgzepJc
Content-Type: application/json

{
    "like": -1,
    "userId": "613b42e8f3575b22aa55d277"
}

###
PUT http://localhost:3000/api/sauces/613b445deecdd273161970b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiNDJlOGYzNTc1YjIyYWE1NWQyNzciLCJpYXQiOjE2MzEyNzM3MzMsImV4cCI6MTYzMTM2MDEzM30.Wg5I92-qKlhdtvpj4EZikhyqx5u8Thf_68WZBgzepJc
Content-Type: application/json

{
    "likes": -11,
    "name": "fzefzeezf"
}